### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/gestures/AndroidGesturesManager;

### ISSUE THREAD

**Issue by lordtao** [maplibre/maplibre-native#2835]
After upgrading maplibre library versions from 11.0.0 to 11.2.0/11.3.0, a crash occurred:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/gestures/AndroidGesturesManager;
at org.maplibre.android.plugins.annotation.DraggableAnnotationController.<init>(DraggableAnnotationController.java:59)
at org.maplibre.android.plugins.annotation.DraggableAnnotationController.getInstance(DraggableAnnotationController.java:29)
at org.maplibre.android.plugins.annotation.SymbolManager.<init>(SymbolManager.java:95)
at org.maplibre.android.plugins.annotation.SymbolManager.<init>(SymbolManager.java:81)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.createSymbolManagers(MapTilerMapManager.kt:576)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.initManagers$lambda$51(MapTilerMapManager.kt:564)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.$r8$lambda$-t4rY2vAZ0sFHPT0WvCsw8fJxg8(Unknown Source:0)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager$$ExternalSyntheticLambda7.onStyleLoaded(D8$$SyntheticClass:0)
at org.maplibre.android.maps.MapLibreMap.getStyle(MapLibreMap.java:125)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.initManagers(MapTilerMapManager.kt:563)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.setListener(MapTilerMapManager.kt:163)
at com.my_project_name.ui.fragment.MapFragment$onMapReady$1.invokeSuspend(MapFragment.kt:670)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
at com.my_project_name.ui.fragment.MapFragment.onMapReady(MapFragment.kt:670)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.onMapReady$lambda$0(MapTilerMapManager.kt:156)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.$r8$lambda$PsmSK3kYxugG1VW2gP5jLI9SHX8(Unknown Source:0)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.loadStyle$lambda$82(MapTilerMapManager.kt:689)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager.$r8$lambda$GQcyAn7Lb1W-eNal9eurpuNfYGc(Unknown Source:0)
at com.my_project_name.map.maptiler.manager.MapTilerMapManager$$ExternalSyntheticLambda9.onStyleLoaded(D8$$SyntheticClass:0)
at org.maplibre.android.maps.MapLibreMap.notifyStyleLoaded(MapLibreMap.java:987)
at org.maplibre.android.maps.MapLibreMap.onFinishLoadingStyle(MapLibreMap.java:229)
at org.maplibre.android.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1348)
at org.maplibre.android.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
at org.maplibre.android.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1145)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:346)
at android.os.Looper.loopOnce(Looper.java:189)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8705)
14:09:33.937 AndroidRuntime                       E  	at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@715141b, Dispatchers.Main.immediate]
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.gestures.AndroidGesturesManager" on path: DexPathList[[zip file "/data/app/~~brIRy9g3Knh2I_EOSvQLcQ==/com.my_project_name-elYGgowXkj2jxnqTz9zM2Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~brIRy9g3Knh2I_EOSvQLcQ==/com.my_project_name-elYGgowXkj2jxnqTz9zM2Q==/lib/x86_64, /data/app/~~brIRy9g3Knh2I_EOSvQLcQ==/com.my_project_name-elYGgowXkj2jxnqTz9zM2Q==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
... 42 more
```

I checked version 11.1.0, it works fine. The problem occurred only in version 11.2.0/11.3.0. Last checked September 9, 2024

# libs.version.toml

maplibre-android-sdk = "11.3.0"
maplibre-android-plugin-annotation-v9 = "3.0.0"

maplibre-android-sdk = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre-android-sdk" }
maplibre-android-plugin-annotation-v9 = { group = "org.maplibre.gl", name = "android-plugin-annotation-v9", version.ref = "maplibre-android-plugin-annotation-v9" }

https://stackoverflow.com/questions/78948389/maplibre11-2-0-crash-didnt-find-class-com-mapbox-android-gestures-androidgestu

**To Reproduce**
Attempt to create SymbolManager after map ready

**Expected behavior**
No crash/all classes are accessible.

**Platform information (please complete the following information):**
Android SDK 34/35

**Comment by louwers** [comment]
Actually this is a different issue.

Can you try the 11.4.0 release?

**Comment by louwers** [comment]
If you update the Annotations plugin to 3.0.1, the issue should be fixed.

**Comment by lordtao** [comment]
Resolved. Thank you!
